import { GoogleGenAI, Type, GenerateContentResponse, Modality } from "@google/genai";
import type { VideoAspectRatio } from '../types';

// IMPORTANT: Do NOT configure an API key here. The key is sourced from process.env.API_KEY.
const getAiClient = () => new GoogleGenAI({ apiKey: process.env.API_KEY });

export const analyzeImage = async (
  base64Image: string,
  mimeType: string,
  usePro: boolean
): Promise<{ description: string; keywords: string }> => {
  const ai = getAiClient();
  const model = usePro ? 'gemini-2.5-pro' : 'gemini-2.5-flash';

  const prompt = `Analyze this image in detail. First, provide a rich, comprehensive description suitable for alt-text. Second, on a new line, provide exactly 2-3 relevant keywords separated by hyphens, suitable for a URL-safe filename. For example: 'keyword-one-keyword-two'.`;

  const imagePart = {
    inlineData: {
      data: base64Image,
      mimeType,
    },
  };

  const response = await ai.models.generateContent({
    model: model,
    contents: { parts: [{ text: prompt }, imagePart] },
    config: usePro ? { thinkingConfig: { thinkingBudget: 32768 } } : {},
  });
  
  const text = response.text.trim();
  const lines = text.split('\n');
  const description = lines.slice(0, -1).join('\n').trim();
  const keywords = lines[lines.length - 1].trim();

  if (!description || !keywords) {
    throw new Error("Failed to parse Gemini's analysis response.");
  }

  return { description, keywords };
};

export const editImage = async (
  base64Image: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  const ai = getAiClient();
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { inlineData: { data: base64Image, mimeType } },
        { text: prompt },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  const imagePart = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
  if (imagePart?.inlineData) {
    return imagePart.inlineData.data;
  }
  throw new Error('No image was generated by the edit request.');
};

export const generateImage = async (
  prompt: string,
  aspectRatio: string
): Promise<string> => {
  const ai = getAiClient();
  const response = await ai.models.generateImages({
    model: 'imagen-4.0-generate-001',
    prompt: prompt,
    config: {
      numberOfImages: 1,
      outputMimeType: 'image/jpeg',
      aspectRatio: aspectRatio,
    },
  });

  if (response.generatedImages && response.generatedImages.length > 0) {
    return response.generatedImages[0].image.imageBytes;
  }
  throw new Error('Image generation failed.');
};

export const generateVideo = async (
  base64Image: string,
  mimeType: string,
  prompt: string,
  aspectRatio: VideoAspectRatio
) => {
  const ai = getAiClient();
  let operation = await ai.models.generateVideos({
    model: 'veo-3.1-fast-generate-preview',
    prompt,
    image: {
      imageBytes: base64Image,
      mimeType,
    },
    config: {
      numberOfVideos: 1,
      resolution: '720p',
      aspectRatio,
    },
  });

  while (!operation.done) {
    await new Promise(resolve => setTimeout(resolve, 10000));
    operation = await ai.operations.getVideosOperation({ operation });
  }

  const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
  if (downloadLink) {
    const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
    const blob = await response.blob();
    return URL.createObjectURL(blob);
  }
  throw new Error('Video generation failed or returned no video URI.');
};

export const performGroundedSearch = async (
  prompt: string,
  location?: GeolocationCoordinates
): Promise<{ text: string; chunks: any[] }> => {
  const ai = getAiClient();
  const useMaps = /nearby|near me|restaurants|locations|places/i.test(prompt);
  
  const config: any = {
    tools: useMaps ? [{ googleMaps: {} }] : [{ googleSearch: {} }],
  };

  if (useMaps && location) {
    config.toolConfig = {
      retrievalConfig: {
        latLng: {
          latitude: location.latitude,
          longitude: location.longitude,
        },
      },
    };
  }

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: prompt,
    config,
  });

  const chunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
  return { text: response.text, chunks };
};
